on:
  push:
    branches: [main, master]
  pull_request:

name: test-coverage

# replace this:
# permissions: read-all
# with explicit perms including OIDC:
permissions:
  contents: read
  id-token: write   # <-- needed for Codecov OIDC

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          print(cov)
          covr::to_cobertura(cov)
        shell: Rscript {0}

      - name: Upload coverage to Codecov (OIDC)
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true          # <-- tell Codecov to authenticate via OIDC
          files: ./cobertura.xml
          plugins: noop
          disable_search: true
          fail_ci_if_error: ${{ github.event_name != 'pull_request' }}
          # no token here
