name: test-coverage

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions: read-all

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Run tests & generate lcov
        run: |
          Rscript -e 'cov <- covr::package_coverage(quiet = FALSE); print(cov); dir.create("coverage", showWarnings = FALSE); covr::lcov(cov, filename = "coverage/lcov.info")'

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info
