name: test-coverage

on:
  push:
    branches: [main, master]
  pull_request:

permissions: read-all

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Run tests & upload to Coveralls
        run: |
          Rscript -e 'cov <- covr::package_coverage(quiet = FALSE); print(cov); covr::coveralls(coverage = cov)'
        env:
          # For public repos on GitHub Actions, this often works without a token,
          # but the most reliable setup is to create COVERALLS_REPO_TOKEN in repo secrets.
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
